# Generated by Django 4.0.1 on 2022-01-22 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_note', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Tasks',
        ),
    ]
