# Generated by Django 3.2.9 on 2022-01-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_note', '0002_rename_task_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
